# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/dct',
                'doc_host': 'https://mshahoyi.github.io',
                'git_url': 'https://github.com/mshahoyi/dct',
                'lib_path': 'dct'},
  'syms': { 'dct.core': { 'dct.core.get_prompt': ('core.html#get_prompt', 'dct/core.py'),
                          'dct.core.get_prompt_suffix': ('core.html#get_prompt_suffix', 'dct/core.py')}}}
